"""one active episode per user

Revision ID: 0b10cd8294bc
Revises: 54ae1243756d
Create Date: 2026-10-02 14:57:19.690903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b10cd8294bc'
down_revision: Union[str, Sequence[str], None] = '54ae1243756d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_episodes_one_active_per_user', 'episodes', ['user_id'], unique=True, postgresql_where=sa.text("status NOT IN ('ready', 'failed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episodes_one_active_per_user', table_name='episodes', postgresql_where=sa.text("status NOT IN ('ready', 'failed')"))
    # ### end Alembic commands ###
