/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Preferences */
        put: operations["save_preferences_me_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Preferences
         * @description Turns what the user's AI answered into a partial Preferences, without saving it.
         */
        post: operations["import_preferences_me_preferences_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/{episode_id}.mp3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audio
         * @description MP3 for <audio> and podcast apps, which cannot send a JWT: the owner's feed token in
         *     `?k=` is the credential (revocable). FileResponse answers Range requests with 206.
         */
        get: operations["get_audio_audio__episode_id__mp3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Episodes */
        get: operations["list_episodes_episodes_get"];
        put?: never;
        /** Generate Now */
        post: operations["generate_now_episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Episode */
        get: operations["get_episode_episodes__episode_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{episode_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_episodes__episode_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EpisodeDetail */
        EpisodeDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s: number | null;
            /** Topics */
            topics: string[];
            /** Failed Stage */
            failed_stage: string | null;
            /** Error */
            error: string | null;
            progress: components["schemas"]["GenerationProgress"];
            /** Hosts */
            hosts: string[];
            /** Script */
            script: {
                [key: string]: unknown;
            } | null;
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["Source"];
            };
            /** Audio Url */
            audio_url: string | null;
        };
        /** EpisodeSummary */
        EpisodeSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Summary */
            summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s: number | null;
            /** Topics */
            topics: string[];
        };
        /**
         * GenerationProgress
         * @description Real numbers from each finished stage, so the UI can show the newsroom at work.
         */
        GenerationProgress: {
            /** Candidates */
            candidates: number;
            /** Outlets */
            outlets: number;
            /** Stories */
            stories: string[];
            /** Articles */
            articles: number;
            /** Issues Found */
            issues_found: number | null;
            /** Issues Fixed */
            issues_fixed: number | null;
            recording: components["schemas"]["Progress"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Host */
        Host: {
            /** Name */
            name: string;
            /** Voice Id */
            voice_id: string;
        };
        /** ImportIn */
        ImportIn: {
            /** Text */
            text: string;
        };
        /** ImportedInterest */
        ImportedInterest: {
            /** Topic */
            topic: string;
            /** Why */
            why?: string | null;
            /**
             * Weight
             * @default 3
             */
            weight: number;
        };
        /**
         * ImportedPreferences
         * @description A partial Preferences: the onboarding fills the rest (format, hosts, schedule).
         */
        ImportedPreferences: {
            /** Interests */
            interests: components["schemas"]["ImportedInterest"][];
            /**
             * Avoid
             * @default []
             */
            avoid: string[];
            /**
             * Sources I Trust
             * @default []
             */
            sources_i_trust: string[];
            /** Language */
            language?: string | null;
            /** Tone */
            tone?: ("casual" | "serious" | "nerdy") | null;
            /** Depth */
            depth?: ("headlines" | "analysis") | null;
        };
        /** Interest */
        Interest: {
            /** Topic */
            topic: string;
            /** Why */
            why?: string | null;
            /**
             * Weight
             * @default 3
             */
            weight: number;
        };
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string | null;
            /** Display Name */
            display_name: string | null;
            preferences: components["schemas"]["Preferences"] | null;
            /** Onboarded */
            onboarded: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Feed Url */
            feed_url: string;
            /** Next Run At */
            next_run_at: string | null;
        };
        /** Preferences */
        Preferences: {
            /** Interests */
            interests: components["schemas"]["Interest"][];
            /**
             * Avoid
             * @default []
             */
            avoid: string[];
            /**
             * Sources I Trust
             * @default []
             */
            sources_i_trust: string[];
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Tone
             * @default casual
             * @enum {string}
             */
            tone: "casual" | "serious" | "nerdy";
            /**
             * Depth
             * @default analysis
             * @enum {string}
             */
            depth: "headlines" | "analysis";
            /**
             * Format
             * @default duo
             * @enum {string}
             */
            format: "solo" | "duo" | "debate";
            /**
             * Duration Min
             * @default 10
             * @enum {integer}
             */
            duration_min: 5 | 10 | 20;
            /** Hosts */
            hosts: components["schemas"]["Host"][];
            /**
             * @default {
             *       "frequency": "daily",
             *       "time": "07:00",
             *       "timezone": "Europe/Madrid"
             *     }
             */
            schedule: components["schemas"]["Schedule"];
        };
        /** PreferencesIn */
        PreferencesIn: {
            preferences: components["schemas"]["Preferences"];
            /**
             * Method
             * @default manual
             * @enum {string}
             */
            method: "import" | "manual";
        };
        /** Progress */
        Progress: {
            /** Done */
            done: number;
            /** Total */
            total: number;
        };
        /** Schedule */
        Schedule: {
            /**
             * Frequency
             * @default daily
             * @enum {string}
             */
            frequency: "off" | "daily" | "weekdays" | "weekly";
            /**
             * Time
             * @default 07:00
             */
            time: string;
            /** Weekday */
            weekday?: number | null;
            /**
             * Timezone
             * @default Europe/Madrid
             */
            timezone: string;
        };
        /** Source */
        Source: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source: string;
            /** Image Url */
            image_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Voice */
        Voice: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Language
             * @enum {string}
             */
            language: "es" | "en";
            /**
             * Gender
             * @enum {string}
             */
            gender: "female" | "male";
            /** Descriptor */
            descriptor: {
                [key: string]: string;
            };
            /** Preview */
            preview: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    save_preferences_me_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_preferences_me_preferences_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportedPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_audio__episode_id__mp3_get: {
        parameters: {
            query: {
                k: string;
            };
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeSummary"][];
                };
            };
        };
    };
    generate_now_episodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetail"];
                };
            };
        };
    };
    get_episode_episodes__episode_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_episodes__episode_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_voices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voice"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
